### ISSUE TITLE
0.74 cannot run without xsensors.xpm

### ISSUE THREAD

**Issue by sibskull** [Mystro256/xsensors#2]
In 0.74 you migrate from xpm to png, but there is no changes in code, that expects old xsensors.xpm:

On Linux:
$ LC_ALL=C xsensors 
No such file or directory: /usr/share/pixmaps/xsensors.xpm
No such file or directory: ./xsensors.xpm
Image file not found in either location!  Exiting!

**Comment by Mystro256** [comment]
Indeed, I had some uncommitted changes I forgot about. I really should be using a better method for marking dev versions. (0.72 is the only real tagged version so far).

Sorry for the late response, I just noticed this now.

**Comment by Mystro256** [comment]
fixed in 0.75
