### ISSUE TITLE
About dialog Segmentation fault

### ISSUE THREAD

**Issue by paulmotey** [Mystro256/xsensors#3]
In "gui.c"
In Procedure "gboolean about_callback(.."
CHANGED 
char* authors [3] = {"Kris Kersey",
                         "Jeremy Newton (mystro256)",
                         "with patches from Nanley Chery"};
TO
char* authors [4] = {"Kris Kersey",
                         "Jeremy Newton (mystro256)",
                         "with patches from Nanley Chery",NULL};
The about box shows up and has no fault.

**Comment by Mystro256** [comment]
Fixed by e7917d186f982cd1e6124eae99dcefceb2dc5577

Thanks!
