### ISSUE TITLE
GdkPixbuf-CRITICAL error

### ISSUE THREAD

**Issue by spvkgn** [Mystro256/xsensors#6]
master GTK3 build fails with error on Ubuntu 18.04 x64
```
(xsensors:19809): GdkPixbuf-CRITICAL **: 16:15:21.699: gdk_pixbuf_new_from_file: assertion 'error == NULL || *error == NULL' failed
```
0.80 release not affected to this issue.

**Comment by Mystro256** [comment]
Thanks for the testing, I know the commit that caused this. I haven't had time to test it.

**Comment by Mystro256** [comment]
I pushed a fix, can you see if that changes anything?
